package com.airdropx.common.enums;

public enum EventType {
    AIRDROP_CREATED, VALIDATION_STARTED, VALIDATION_COMPLETED,
    JOB_CREATED, JOB_STARTED, PROGRESS_UPDATED, RECIPIENT_FAILED,
    AIRDROP_COMPLETED, AIRDROP_CANCELLED,
    CLAIM_SUBMITTED, CLAIM_APPROVED, CLAIM_REJECTED
}
